/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entidades.*;
import Listas.*;
import Persistencia.DAO.*;
import java.util.ArrayList;
import java.util.List;

import Controlador.ControladorPersonas;
import Controlador.ControladorEstudiantes;
import Entidades.*;
import Listas.CursosProfesores;
import Persistencia.DAO.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Ventana principal refactorizada siguiendo el patrón MVC
 * Ahora actúa como un coordinador que delega a paneles específicos
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    // Paneles específicos para cada funcionalidad
    private JPanelPersonas panelPersonas;
    private JPanelEstudiantes panelEstudiantes;
    
    // Controladores específicos
    private ControladorPersonas controladorPersonas;
    private ControladorEstudiantes controladorEstudiantes;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        inicializarPanelesYControladores();
    }
    
    /**
     * Inicializa los paneles específicos y sus controladores
     * Aplica el patrón Creator - VentanaPrincipal es responsable de crear sus componentes
     */
    private void inicializarPanelesYControladores() {
        // Crear paneles específicos
        panelPersonas = new JPanelPersonas();
        panelEstudiantes = new JPanelEstudiantes();
        
        // Crear controladores específicos
        controladorPersonas = new ControladorPersonas(panelPersonas);
        controladorEstudiantes = new ControladorEstudiantes(panelEstudiantes);
        
        // Asignar controladores a las vistas
        panelPersonas.setControlador(controladorPersonas);
        panelEstudiantes.setControlador(controladorEstudiantes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorPrincipal = new javax.swing.JPanel();
        TPPrincipal = new javax.swing.JTabbedPane();
        
        // Los demás paneles temporalmente mantendremos algunos por compatibilidad
        ContenedorCursoProfesor = new javax.swing.JPanel();
        TPCursoProfesor = new javax.swing.JTabbedPane();
        InscribirCursoProfesor = new javax.swing.JPanel();
        EliminarCursoProfesor = new javax.swing.JPanel();
        ContenedorInscripciones = new javax.swing.JPanel();
        TPInscripciones = new javax.swing.JTabbedPane();
        IncribirIncripcion = new javax.swing.JPanel();
        EliminarIncripcion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        // Configuración básica de componentes que mantuvimos
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaProgramas = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaCursos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContenedorPrincipal.setBackground(new java.awt.Color(249, 248, 250));

        TPPrincipal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TPPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPPrincipalMouseClicked(evt);
            }
        });

        // Agregar los nuevos paneles refactorizados
        TPPrincipal.addTab("Personas", panelPersonas);
        TPPrincipal.addTab("Estudiantes", panelEstudiantes);

        javax.swing.GroupLayout IncripcionPersonasLayout = new javax.swing.GroupLayout(IncripcionPersonas);
        IncripcionPersonas.setLayout(IncripcionPersonasLayout);
        IncripcionPersonasLayout.setHorizontalGroup(
            IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncripcionPersonasLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncripcionPersonasLayout.createSequentialGroup()
                        .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombresPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApellidosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IncripcionPersonasLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(BTNIncribirPersona)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        IncripcionPersonasLayout.setVerticalGroup(
            IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncripcionPersonasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombresPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ApellidosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IncripcionPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EmailPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNIncribirPersona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPPersonas.addTab("Inscribir", IncripcionPersonas);

        jLabel13.setText("Listado de Personas");

        ListaPersonas.setEditable(false);
        ListaPersonas.setColumns(20);
        ListaPersonas.setRows(5);
        jScrollPane1.setViewportView(ListaPersonas);

        jLabel14.setText("ID");

        jButton1.setText("Eliminar Persona");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel24.setText("ID -- NOMBRES APELLIDOS");

        javax.swing.GroupLayout EliminarPersonasLayout = new javax.swing.GroupLayout(EliminarPersonas);
        EliminarPersonas.setLayout(EliminarPersonasLayout);
        EliminarPersonasLayout.setHorizontalGroup(
            EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarPersonasLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EliminarPersonasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)))
                .addGap(62, 62, 62))
            .addGroup(EliminarPersonasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarPersonasLayout.setVerticalGroup(
            EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarPersonasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(2, 2, 2)
                .addGroup(EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarPersonasLayout.createSequentialGroup()
                        .addGroup(EliminarPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(IDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TPPersonas.addTab("Eliminar", EliminarPersonas);

        javax.swing.GroupLayout ContenedorPersonasLayout = new javax.swing.GroupLayout(ContenedorPersonas);
        ContenedorPersonas.setLayout(ContenedorPersonasLayout);
        ContenedorPersonasLayout.setHorizontalGroup(
            ContenedorPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPPersonas)
                .addContainerGap())
        );
        ContenedorPersonasLayout.setVerticalGroup(
            ContenedorPersonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPersonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPPersonas)
                .addContainerGap())
        );

        TPPrincipal.addTab("Personas", ContenedorPersonas);

        jLabel7.setText("Inscribir Estudiante");

        jLabel9.setText("ID");

        jLabel10.setText("Nombres");

        jLabel11.setText("Apellidos");

        jLabel12.setText("Email");

        BTNIncribirEstudiante.setText("Incribir");
        BTNIncribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIncribirEstudianteActionPerformed(evt);
            }
        });

        jLabel16.setText("Programa");

        jLabel17.setText("Activo");

        CBActivo.setSelected(true);

        jLabel18.setText("Promedio");

        jLabel27.setText("Codigo");

        javax.swing.GroupLayout ContenedorEstudiantesLayout = new javax.swing.GroupLayout(ContenedorEstudiantes);
        ContenedorEstudiantes.setLayout(ContenedorEstudiantesLayout);
        ContenedorEstudiantesLayout.setHorizontalGroup(
            ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(CBActivo))
                            .addComponent(IDEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(NombresEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(ApellidosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(EmailEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(Promedio, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(IDPrograma)
                            .addComponent(Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(BTNIncribirEstudiante))
                    .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 251, Short.MAX_VALUE))
        );
        ContenedorEstudiantesLayout.setVerticalGroup(
            ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorEstudiantesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NombresEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ApellidosEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(IDPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CBActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Promedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNIncribirEstudiante)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        TPPrincipal.addTab("Estudiantes", ContenedorEstudiantes);

        jLabel8.setText("Incribir Profesor");

        jLabel19.setText("ID");

        jLabel20.setText("Nombres");

        jLabel21.setText("Apellidos");

        jLabel22.setText("Email");

        BTNIncribirProfesor.setText("Incribir");
        BTNIncribirProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIncribirProfesorActionPerformed(evt);
            }
        });

        jLabel23.setText("Tipo de contrato");

        TipoContrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nomina", "Prestacion de Servicios" }));

        javax.swing.GroupLayout ContenedorProfesoresLayout = new javax.swing.GroupLayout(ContenedorProfesores);
        ContenedorProfesores.setLayout(ContenedorProfesoresLayout);
        ContenedorProfesoresLayout.setHorizontalGroup(
            ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorProfesoresLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenedorProfesoresLayout.createSequentialGroup()
                        .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDProfesor)
                            .addComponent(NombresProfesor)
                            .addComponent(ApellidosProfesor)
                            .addComponent(EmailProfesor)
                            .addComponent(TipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProfesoresLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProfesoresLayout.createSequentialGroup()
                                .addComponent(BTNIncribirProfesor)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorProfesoresLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)))))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        ContenedorProfesoresLayout.setVerticalGroup(
            ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorProfesoresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(IDProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(NombresProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ApellidosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(EmailProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContenedorProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TipoContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNIncribirProfesor)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        TPPrincipal.addTab("Profesores", ContenedorProfesores);

        TPCursoProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TPCursoProfesorMouseClicked(evt);
            }
        });

        jLabel15.setText("Profesor");

        CBProfesores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel30.setText("año");

        jLabel31.setText("semestre");

        jLabel32.setText("curso");

        anoCursoProfesor.setText("2025");
        anoCursoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoCursoProfesorActionPerformed(evt);
            }
        });

        semestreCursoProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        CBCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BTNInscribirCursoProfesor.setText("Inscribir");
        BTNInscribirCursoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInscribirCursoProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InscribirCursoProfesorLayout = new javax.swing.GroupLayout(InscribirCursoProfesor);
        InscribirCursoProfesor.setLayout(InscribirCursoProfesorLayout);
        InscribirCursoProfesorLayout.setHorizontalGroup(
            InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscribirCursoProfesorLayout.createSequentialGroup()
                .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InscribirCursoProfesorLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30)
                            .addComponent(jLabel15)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBProfesores, 0, 175, Short.MAX_VALUE)
                            .addComponent(anoCursoProfesor)
                            .addComponent(semestreCursoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(InscribirCursoProfesorLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(BTNInscribirCursoProfesor)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        InscribirCursoProfesorLayout.setVerticalGroup(
            InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InscribirCursoProfesorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CBProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(anoCursoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(semestreCursoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InscribirCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(CBCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(BTNInscribirCursoProfesor)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        TPCursoProfesor.addTab("Inscribir", InscribirCursoProfesor);

        ListaCursosProfesor.setEditable(false);
        ListaCursosProfesor.setColumns(20);
        ListaCursosProfesor.setRows(5);
        jScrollPane4.setViewportView(ListaCursosProfesor);

        jLabel33.setText("Lista de Cursos Profesor");

        jLabel34.setText("CURSO - PROFESOR - PERIODO");

        javax.swing.GroupLayout EliminarCursoProfesorLayout = new javax.swing.GroupLayout(EliminarCursoProfesor);
        EliminarCursoProfesor.setLayout(EliminarCursoProfesorLayout);
        EliminarCursoProfesorLayout.setHorizontalGroup(
            EliminarCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarCursoProfesorLayout.createSequentialGroup()
                .addGroup(EliminarCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EliminarCursoProfesorLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EliminarCursoProfesorLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel34)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarCursoProfesorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(246, 246, 246))
        );
        EliminarCursoProfesorLayout.setVerticalGroup(
            EliminarCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarCursoProfesorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        TPCursoProfesor.addTab("Eliminar", EliminarCursoProfesor);

        javax.swing.GroupLayout ContenedorCursoProfesorLayout = new javax.swing.GroupLayout(ContenedorCursoProfesor);
        ContenedorCursoProfesor.setLayout(ContenedorCursoProfesorLayout);
        ContenedorCursoProfesorLayout.setHorizontalGroup(
            ContenedorCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorCursoProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPCursoProfesor)
                .addContainerGap())
        );
        ContenedorCursoProfesorLayout.setVerticalGroup(
            ContenedorCursoProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorCursoProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPCursoProfesor)
                .addContainerGap())
        );

        TPPrincipal.addTab("Curso Profesor", ContenedorCursoProfesor);

        javax.swing.GroupLayout IncribirIncripcionLayout = new javax.swing.GroupLayout(IncribirIncripcion);
        IncribirIncripcion.setLayout(IncribirIncripcionLayout);
        IncribirIncripcionLayout.setHorizontalGroup(
            IncribirIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        IncribirIncripcionLayout.setVerticalGroup(
            IncribirIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        TPInscripciones.addTab("Inscribir", IncribirIncripcion);

        javax.swing.GroupLayout EliminarIncripcionLayout = new javax.swing.GroupLayout(EliminarIncripcion);
        EliminarIncripcion.setLayout(EliminarIncripcionLayout);
        EliminarIncripcionLayout.setHorizontalGroup(
            EliminarIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        EliminarIncripcionLayout.setVerticalGroup(
            EliminarIncripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );

        TPInscripciones.addTab("Eliminar", EliminarIncripcion);

        javax.swing.GroupLayout ContenedorInscripcionesLayout = new javax.swing.GroupLayout(ContenedorInscripciones);
        ContenedorInscripciones.setLayout(ContenedorInscripcionesLayout);
        ContenedorInscripcionesLayout.setHorizontalGroup(
            ContenedorInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPInscripciones)
                .addContainerGap())
        );
        ContenedorInscripcionesLayout.setVerticalGroup(
            ContenedorInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorInscripcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPInscripciones)
                .addContainerGap())
        );

        TPPrincipal.addTab("Inscripciones", ContenedorInscripciones);

        jLabel25.setText("Lista de Programas");

        jLabel26.setText("ID - NOMBRE");

        ListaProgramas.setEditable(false);
        ListaProgramas.setColumns(20);
        ListaProgramas.setRows(5);
        jScrollPane2.setViewportView(ListaProgramas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(14, 14, 14)))
                .addContainerGap(271, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        TPPrincipal.addTab("Programas", jPanel1);

        jLabel28.setText("Lista de Cursos");

        jLabel29.setText("ID - NOMBRE - PROGRAMA");

        ListaCursos.setEditable(false);
        ListaCursos.setColumns(20);
        ListaCursos.setRows(5);
        jScrollPane3.setViewportView(ListaCursos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel29)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        TPPrincipal.addTab("Cursos", jPanel2);

        javax.swing.GroupLayout ContenedorPrincipalLayout = new javax.swing.GroupLayout(ContenedorPrincipal);
        ContenedorPrincipal.setLayout(ContenedorPrincipalLayout);
        ContenedorPrincipalLayout.setHorizontalGroup(
            ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPPrincipal)
                .addContainerGap())
        );
        ContenedorPrincipalLayout.setVerticalGroup(
            ContenedorPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TPPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNIncribirPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIncribirPersonaActionPerformed
        // TODO add your handling code here:
        Double id = Double.valueOf(IDPersona.getText());
        String nombres = NombresPersona.getText();
        String apellidos = ApellidosPersona.getText();
        String email = EmailPersona.getText();
        persona = new Persona(id, nombres, apellidos, email);
    }//GEN-LAST:event_BTNIncribirPersonaActionPerformed

    private void BTNIncribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIncribirEstudianteActionPerformed
        Double id = Double.valueOf(IDEstudiante.getText());
        String nombres = NombresEstudiante.getText();
        String apellidos = ApellidosEstudiante.getText();
        String email = EmailEstudiante.getText();
        Double codigo = Double.valueOf(Codigo.getText());
        programa = programaDao.obtenerPorId(Double.valueOf(IDPrograma.getText()));
        boolean activo = CBActivo.isSelected();
        Double promedio = Double.valueOf(Promedio.getText());

        estudiante = new Estudiante(id, nombres, apellidos, email, codigo, programa, activo, promedio);
        estudianteDao.crear(estudiante);

    }//GEN-LAST:event_BTNIncribirEstudianteActionPerformed

    private void BTNIncribirProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIncribirProfesorActionPerformed
        Double id = Double.valueOf(IDProfesor.getText());
        String nombres = NombresProfesor.getText();
        String apellidos = ApellidosProfesor.getText();
        String email = EmailProfesor.getText();
        String tipoContrato = (String) TipoContrato.getSelectedItem();

        profesor = new Profesor(id, nombres, apellidos, email, tipoContrato);
        profesorDao.crear(profesor);
    }//GEN-LAST:event_BTNIncribirProfesorActionPerformed

    private void IDPersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDPersonaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_IDPersonaKeyTyped

    private void NombresPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresPersonaActionPerformed

    private void EmailPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPersonaActionPerformed

    private void ApellidosPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosPersonaActionPerformed

    private void TPPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPPersonasMouseClicked
        actualizarListaPersonas();
    }//GEN-LAST:event_TPPersonasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        personaDao.eliminar(Double.valueOf(IDEliminar.getText()));
        actualizarListaPersonas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TPPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPPrincipalMouseClicked
        actualizarListaProgramas();
        actualizarListaCursos();
        actualizarListaCursosProfesor();
    }//GEN-LAST:event_TPPrincipalMouseClicked

    private void TPCursoProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TPCursoProfesorMouseClicked
        actualizarComboBoxProfesores();
        actualizarComboBoxCursos();
    }//GEN-LAST:event_TPCursoProfesorMouseClicked

    private void anoCursoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoCursoProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoCursoProfesorActionPerformed

    private void BTNInscribirCursoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInscribirCursoProfesorActionPerformed
        profesor = arrayProfesor.get(CBProfesores.getSelectedIndex());
        int ano = Integer.parseInt(anoCursoProfesor.getText());
        String semestreString = (String) semestreCursoProfesor.getSelectedItem();
        int semestreInt = Integer.parseInt(semestreString);
        curso = arrayCurso.get(CBCursos.getSelectedIndex());
        cursoProfesor = new CursoProfesor(profesor, ano, semestreInt, curso);
        actualizarListaCursosProfesor();
    }//GEN-LAST:event_BTNInscribirCursoProfesorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidosEstudiante;
    private javax.swing.JTextField ApellidosPersona;
    private javax.swing.JTextField ApellidosProfesor;
    private javax.swing.JButton BTNIncribirEstudiante;
    private javax.swing.JButton BTNIncribirPersona;
    private javax.swing.JButton BTNIncribirProfesor;
    private javax.swing.JButton BTNInscribirCursoProfesor;
    private javax.swing.JCheckBox CBActivo;
    private javax.swing.JComboBox<String> CBCursos;
    private javax.swing.JComboBox<String> CBProfesores;
    private javax.swing.JTextField Codigo;
    private javax.swing.JPanel ContenedorCursoProfesor;
    private javax.swing.JPanel ContenedorEstudiantes;
    private javax.swing.JPanel ContenedorInscripciones;
    private javax.swing.JPanel ContenedorPersonas;
    private javax.swing.JPanel ContenedorPrincipal;
    private javax.swing.JPanel ContenedorProfesores;
    private javax.swing.JPanel EliminarCursoProfesor;
    private javax.swing.JPanel EliminarIncripcion;
    private javax.swing.JPanel EliminarPersonas;
    private javax.swing.JTextField EmailEstudiante;
    private javax.swing.JTextField EmailPersona;
    private javax.swing.JTextField EmailProfesor;
    private javax.swing.JTextField IDEliminar;
    private javax.swing.JTextField IDEstudiante;
    private javax.swing.JTextField IDPersona;
    private javax.swing.JTextField IDProfesor;
    private javax.swing.JTextField IDPrograma;
    private javax.swing.JPanel IncribirIncripcion;
    private javax.swing.JPanel IncripcionPersonas;
    private javax.swing.JPanel InscribirCursoProfesor;
    private javax.swing.JTextArea ListaCursos;
    private javax.swing.JTextArea ListaCursosProfesor;
    private javax.swing.JTextArea ListaPersonas;
    private javax.swing.JTextArea ListaProgramas;
    private javax.swing.JTextField NombresEstudiante;
    private javax.swing.JTextField NombresPersona;
    private javax.swing.JTextField NombresProfesor;
    private javax.swing.JTextField Promedio;
    private javax.swing.JTabbedPane TPCursoProfesor;
    private javax.swing.JTabbedPane TPInscripciones;
    private javax.swing.JTabbedPane TPPersonas;
    private javax.swing.JTabbedPane TPPrincipal;
    private javax.swing.JComboBox<String> TipoContrato;
    private javax.swing.JTextField anoCursoProfesor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> semestreCursoProfesor;
    // End of variables declaration//GEN-END:variables

    PersonaDAO personaDao = new PersonaDAO();
    Persona persona;
    List<Persona> arrayPersona = new ArrayList<>();

    EstudianteDAO estudianteDao = new EstudianteDAO();
    Estudiante estudiante;
    List<Estudiante> arrayEstudiante = new ArrayList<>();

    ProfesorDAO profesorDao = new ProfesorDAO();
    Profesor profesor;
    List<Profesor> arrayProfesor = new ArrayList<>();

    ProgramaDAO programaDao = new ProgramaDAO();
    Programa programa;
    List<Programa> arrayPrograma = new ArrayList<>();

    CursoDAO cursoDao = new CursoDAO();
    Curso curso;
    List<Curso> arrayCurso = new ArrayList<>();
    
    CursosProfesores cursoProfesoresDao = new CursosProfesores();
    CursoProfesor cursoProfesor;
    List<CursoProfesor> arrayCursoProfesor = new ArrayList<>();
    
    
    private void actualizarComboBoxCursos() {
        CBCursos.removeAllItems();
        arrayCurso = cursoDao.obtenerTodos();
        for (Curso aux : arrayCurso) {
            CBCursos.addItem(aux.getNombre());
        }
    }
    
    private void actualizarComboBoxProfesores() {
        CBProfesores.removeAllItems();
        arrayProfesor = profesorDao.obtenerTodos();
        for (Profesor aux : arrayProfesor) {
            CBProfesores.addItem(aux.getNombres());
        }
    }
    
    private void actualizarListaCursos() {
        ListaCursos.setText("");
        arrayCurso = cursoDao.obtenerTodos();
        for (Curso aux : arrayCurso) {
            ListaCursos.append(String.valueOf(aux.getId())
                    + " -- " + aux.getNombre() +
                      " -- " + aux.getPrograma().getNombre() + "\n");

        }
    }
    
    private void actualizarListaCursosProfesor() {
        ListaCursosProfesor.setText("");
        arrayCursoProfesor = cursoProfesoresDao.getListado();
        for (CursoProfesor aux : arrayCursoProfesor) {
            ListaCursosProfesor.append(aux.getCurso().getNombre()
                    + " -- " + aux.getProfesor().getNombres()+
                      " -- " + aux.getAno() + "-" + aux.getSemestre() + "\n");

        }
    }

    private void actualizarListaPersonas() {
        ListaPersonas.setText("");
        arrayPersona = personaDao.obtenerTodos();
        for (Persona aux : arrayPersona) {
            ListaPersonas.append(String.valueOf(aux.getId())
                    + " -- " + aux.getNombres()
                    + " " + aux.getApellidos() + "\n");

        }
    }

    private void actualizarListaProgramas() {
        ListaProgramas.setText("");
        arrayPrograma = programaDao.obtenerTodos();
        for (Programa aux : arrayPrograma) {
            ListaProgramas.append(String.valueOf(aux.getId())
                    + " -- " + aux.getNombre() + "\n");

        }
    }
    
}
