version: "3.8"

services:
  mysql:
    image: mysql:oraclelinux9
    container_name: mysql-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle-app
    environment:
      ORACLE_PASSWORD: root
      ORACLE_ALLOW_REMOTE: "true"
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s system/root@//localhost:1521/XE || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  oracle_data:
